module.exports = {
  TRANSITION_DURATION: 333,
  TRANSITION_DURATION_QUICK: 100,
  RECIPE_LIST_ITEM_HEIGHT: 45,
  RECIPE_LIST_HEADER_HEIGHT: 18,
  INGREDIENTS_LIST_ITEM_HEIGHT: 45, // Includes border...
  INGREDIENTS_LIST_GROUP_HEIGHT_OFFSET: -1 // ...except for the first item.
};